"""HTML real de dois cards de voo do site principal da Azul, capturados ao
vivo em 21/08/2026 (busca GIG->MCO, 22/08 a 14/09/2026, pontos). Um card
disponível e um indisponível — nada aqui foi reconstruído de memória, é
`outerHTML` de verdade lido do DOM.
"""

CARD_DISPONIVEL = '''<div id="QUR_NDQ1MH4gfn5HSUd_MDgvMjIvMjAyNiAwNTo0NX5WQ1B_MDgvMjIvMjAyNiAwNzowMH5_XkFEfjg3MDZ_IH5_VkNQfjA4LzIyLzIwMjYgMDk6NTV_TUNPfjA4LzIyLzIwMjYgMTg6MDB_fg--" class="flight-card css-c3x279"><div class="card flight-card__container css-6i4tbq" role="button" tabindex="0"><div class="flight-card__info left-container css-2888k0" tabindex="0" role="button" data-leg-capacity="136" data-leg-lid="136" data-leg-sold="119" data-leg-remaining-seats="17"><div class="info"><div class="info-container css-1dvehwi"><h4 aria-hidden="true" class="departure css-qxyl5a" aria-label="Horário de partida 05:45">05:45<span class="iata-day">GIG</span></h4><h4 aria-hidden="true" class="arrival css-10qt17w">18:00<span class="iata-day arrival">MCO</span></h4><p class="flight-leg-info"><button type="button" class="css-5et3bs"><span class="css-tkxfs6">1 conexão    •  Voo 4450</span></button></p></div><button type="button" class="duration css-12pqtfr">Duração: <strong>13h 15m</strong></button></div></div><div class="flight-card__fare right-container css-h48jfl" tabindex="0" role="button"><div class="fare-container left false css-3nf628"><p class="hide-on-desktop from css-1cviwo3"><p class="initial css-7fbpek">338000 pontos</p></p></div><div class="fare-container right css-1rrea4n"><div class="fare css-34x9bu"><div><p class="initial css-7fbpek">338000 pontos</p><h4 class="current css-2db79l" data-test-id="fare-price fare-price-with-points">334.620<span class="points">pontos</span></h4><p class="condition css-1nnw7nu">ou 33.462 pontos + R$&nbsp;3.691,89 </p></div></div></div></div></div>'''

CARD_INDISPONIVEL = '''<div id="QUR_NDIwNX4gfn5HSUd_MDgvMjIvMjAyNiAxNDo0NX5DTkZ_MDgvMjIvMjAyNiAxNTo1MH5_XkFEfjg3MzB_IH5_Q05GfjA4LzIzLzIwMjYgMTI6MjV_TUNPfjA4LzIzLzIwMjYgMjA6MzB_fg--" class="flight-card css-1fmxv98"><div class="card flight-card__container css-1dejfke" role="button" tabindex="0"><div class="flight-card__info left-container css-2888k0" tabindex="0" role="button" data-leg-capacity="118" data-leg-lid="125" data-leg-sold="117" data-leg-remaining-seats="8"><div class="info"><div class="info-container css-1ffqffe"><h4 aria-hidden="true" class="departure css-kznatk" aria-label="Horário de partida 14:45">14:45<span class="iata-day">GIG • 22/08</span></h4><h4 aria-hidden="true" class="arrival css-ovuxqz">20:30<span class="iata-day arrival">MCO • 23/08</span></h4><p class="flight-leg-info"><button type="button" class="css-uhxk0a"><span class="css-tkxfs6">1 conexão    •  Voo 4205</span></button></p></div></div></div><div class="flight-card__fare right-container css-h48jfl" tabindex="0" aria-label="Indisponível" role="button"><div class="fare-container left false css-3nf628"></div><div class="fare-container right css-1y9g5p7"><div class="fareIndex-1"><div role="button" tabindex="0" class="css-18wb4my"><div class="css-1pjg447"><span>Indisponível</span></div></div></div></div></div></div>'''
